theme: jekyll-theme-minimal
logo: /assets/img/logo.png
title: Hank de Wit
description: ""
email: hdewit at people net au
blank_title: true
favicon: true
show_downloads: false
color-scheme: auto

sidebar:
  - name: Home
    icon: <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" role="img" style="vertical-align:-0.125em;" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"> <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/> </svg>
    link: /
  - name: mtDNA
    icon: <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" role="img" style="vertical-align:-0.125em;" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"> <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/> </svg>
    link: /mtdna
  - name: CFS Maps
    icon: <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" role="img" style="vertical-align:-0.125em;" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"> <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/> </svg>
    link: /cfs_map/geographic_converter.shtml